#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -o size=1024k -t tmpfs none /run
mount -o size=8192k -t tmpfs none /tmp
mkdir -p /var/log
mount -o size=32768k -t tmpfs none /var/log
mount -t devtmpfs none /dev
mkdir -p /storage
chmod a+rx /storage

mkdir -p /sys/fs/cgroup
mount -t tmpfs none -o rw,nosuid,nodev,noexec,mode=755 /sys/fs/cgroup

for i in cpu memory; do
	mkdir /sys/fs/cgroup/${i}
	mount -t cgroup ${i} -o ${i} /sys/fs/cgroup/${i}
done

mount -o remount,ro /sys/fs/cgroup

echo 0 > /proc/sys/kernel/printk

echo "Starting up Unofficial Embedded Boinc linux"
echo -n "Platform: "
uname -a

mkdir /dev/pts
mkdir /dev/shm
mount -t devpts -o gid=4,mode=620 none /dev/pts
mount -t tmpfs none /dev/shm

echo "UEBO: Loading kernel modules"
for i in $(cat /etc/sysconfig/modules); do
        modprobe ${i}
done

sleep 2

echo "UEBO Init: looking for all possible local storages..."
for i in $(ls /dev/mmcblk* /dev/sd* /dev/hd*); do
	e2fsck ${i} -p
	echo -n "> ${i} ... "
	label=$(e2label ${i} || "")
	echo -n "${label} "
	case x"${label}" in
		xstorage)
			mount ${i} /storage
			echo "-> /storage"
			;;
		*)
			echo "skipped"
			;;
	esac
done

if [ -f /storage/modules ]; then
	echo "UEBO: Loading kernel modules stage 2"
	for i in $(cat /conf/modules); do
        	modprobe ${i}
	done
fi

exec /sbin/runit-init
