#!/bin/sh
exec 2>&1

if [ ! -f /conf/dropbear/ed25519_hostkey ]; then
	mkdir -p /conf/dropbear
	dropbearkey -t ed25519 -f /conf/dropbear/ed25519_hostkey
fi


exec /usr/sbin/dropbear -F -r /conf/dropbear/ed25519_hostkey
