#!/bin/sh

# check that boinc-client is actually mounted from a permanent storage
mountpoint /var/lib/boinc-client -q || exit 1

if ! getent group boinc; then
	addgroup -S boinc
fi

if ! getent passwd boinc; then
	 adduser -h /var/lib/boinc-client -s /usr/sbin/nologin -G boinc -S -D -H boinc
fi

mkdir -p /var/lib/boinc-client /etc/boinc-client
chown -R boinc:boinc /var/lib/boinc-client

echo "data_dir=/var/lib/boinc-client" > /etc/boinc-client/config.properties

if [ ! -d /sys/fs/cgroup/memory/boinc ]; then
	mkdir /sys/fs/cgroup/memory/boinc
fi

memlimit=$(($(cat /proc/meminfo | grep MemTotal | awk '{print $2}')*900))
echo $memlimit > /sys/fs/cgroup/memory/boinc/memory.limit_in_bytes

exec cgexec -g memory:boinc chpst -uboinc /usr/bin/boinc --dir /var/lib/boinc-client
